on: [ push ]
jobs:
  build:
    runs-on: native
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: ./.forgejo/actions/build
        name: Build
      - uses: ./.forgejo/actions/scan
        name: Scan
      - uses: ./.forgejo/actions/test
        name: Test