// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/satellite.proto

package satellitepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_IDLE    Status = 0
	Status_PLAYING Status = 1
	Status_PAUSED  Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "IDLE",
		1: "PLAYING",
		2: "PAUSED",
	}
	Status_value = map[string]int32{
		"IDLE":    0,
		"PLAYING": 1,
		"PAUSED":  2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_satellite_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_satellite_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_satellite_proto_rawDescGZIP(), []int{0}
}

type CommandType int32

const (
	CommandType_PLAY             CommandType = 0
	CommandType_PAUSE            CommandType = 1
	CommandType_STOP             CommandType = 2
	CommandType_SEEK             CommandType = 3
	CommandType_SET_VOLUME       CommandType = 4
	CommandType_SET_AUDIO_DEVICE CommandType = 5
	CommandType_RESUME           CommandType = 6
	CommandType_SET_REPLAY_GAIN  CommandType = 7
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "PLAY",
		1: "PAUSE",
		2: "STOP",
		3: "SEEK",
		4: "SET_VOLUME",
		5: "SET_AUDIO_DEVICE",
		6: "RESUME",
		7: "SET_REPLAY_GAIN",
	}
	CommandType_value = map[string]int32{
		"PLAY":             0,
		"PAUSE":            1,
		"STOP":             2,
		"SEEK":             3,
		"SET_VOLUME":       4,
		"SET_AUDIO_DEVICE": 5,
		"RESUME":           6,
		"SET_REPLAY_GAIN":  7,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_satellite_proto_enumTypes[1].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_proto_satellite_proto_enumTypes[1]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_satellite_proto_rawDescGZIP(), []int{1}
}

type SatelliteMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SatelliteMessage_Registration
	//	*SatelliteMessage_Heartbeat
	//	*SatelliteMessage_State
	//	*SatelliteMessage_Devices
	//	*SatelliteMessage_TrackEnded
	Payload       isSatelliteMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SatelliteMessage) Reset() {
	*x = SatelliteMessage{}
	mi := &file_proto_satellite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SatelliteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatelliteMessage) ProtoMessage() {}

func (x *SatelliteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_satellite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatelliteMessage.ProtoReflect.Descriptor instead.
func (*SatelliteMessage) Descriptor() ([]byte, []int) {
	return file_proto_satellite_proto_rawDescGZIP(), []int{0}
}

func (x *SatelliteMessage) GetPayload() isSatelliteMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SatelliteMessage) GetRegistration() *Registration {
	if x != nil {
		if x, ok := x.Payload.(*SatelliteMessage_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

func (x *SatelliteMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*SatelliteMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *SatelliteMessage) GetState() *PlayerState {
	if x != nil {
		if x, ok := x.Payload.(*SatelliteMessage_State); ok {
			return x.State
		}
	}
	return nil
}

func (x *SatelliteMessage) GetDevices() *DeviceList {
	if x != nil {
		if x, ok := x.Payload.(*SatelliteMessage_Devices); ok {
			return x.Devices
		}
	}
	return nil
}

func (x *SatelliteMessage) GetTrackEnded() *TrackEnded {
	if x != nil {
		if x, ok := x.Payload.(*SatelliteMessage_TrackEnded); ok {
			return x.TrackEnded
		}
	}
	return nil
}

type isSatelliteMessage_Payload interface {
	isSatelliteMessage_Payload()
}

type SatelliteMessage_Registration struct {
	Registration *Registration `protobuf:"bytes,1,opt,name=registration,proto3,oneof"`
}

type SatelliteMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type SatelliteMessage_State struct {
	State *PlayerState `protobuf:"bytes,3,opt,name=state,proto3,oneof"`
}

type SatelliteMessage_Devices struct {
	Devices *DeviceList `protobuf:"bytes,4,opt,name=devices,proto3,oneof"`
}

type SatelliteMessage_TrackEnded struct {
	TrackEnded *TrackEnded `protobuf:"bytes,5,opt,name=track_ended,json=trackEnded,proto3,oneof"`
}

func (*SatelliteMessage_Registration) isSatelliteMessage_Payload() {}

func (*SatelliteMessage_Heartbeat) isSatelliteMessage_Payload() {}

func (*SatelliteMessage_State) isSatelliteMessage_Payload() {}

func (*SatelliteMessage_Devices) isSatelliteMessage_Payload() {}

func (*SatelliteMessage_TrackEnded) isSatelliteMessage_Payload() {}

type Registration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Devices       []*AudioDevice         `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_proto_satellite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_satellite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_proto_satellite_proto_rawDescGZIP(), []int{1}
}

func (x *Registration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Registration) GetDevices() []*AudioDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type AudioDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // mpv device string, e.g. "alsa/hw:0"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // human-readable label
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioDevice) Reset() {
	*x = AudioDevice{}
	mi := &file_proto_satellite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioDevice) ProtoMessage() {}

func (x *AudioDevice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_satellite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioDevice.ProtoReflect.Descriptor instead.
func (*AudioDevice) Descriptor() ([]byte, []int) {
	return file_proto_satellite_proto_rawDescGZIP(), []int{2}
}

func (x *AudioDevice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AudioDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=satellite.Status" json:"status,omitempty"`
	Position      float64                `protobuf:"fixed64,2,opt,name=position,proto3" json:"position,omitempty"`
	Duration      float64                `protobuf:"fixed64,3,opt,name=duration,proto3" json:"duration,omitempty"`
	CurrentUrl    string                 `protobuf:"bytes,4,opt,name=current_url,json=currentUrl,proto3" json:"current_url,omitempty"`
	Volume        int32                  `protobuf:"varint,5,opt,name=volume,proto3" json:"volume,omitempty"`
	AudioDevice   string                 `protobuf:"bytes,6,opt,name=audio_device,json=audioDevice,proto3" json:"audio_device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_proto_satellite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_satellite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_proto_satellite_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerState) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_IDLE
}

func (x *PlayerState) GetPosition() float64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *PlayerState) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *PlayerState) GetCurrentUrl() string {
	if x != nil {
		return x.CurrentUrl
	}
	return ""
}

func (x *PlayerState) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *PlayerState) GetAudioDevice() string {
	if x != nil {
		return x.AudioDevice
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_satellite_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_satellite_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_satellite_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type DeviceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*AudioDevice         `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceList) Reset() {
	*x = DeviceList{}
	mi := &file_proto_satellite_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceList) ProtoMessage() {}

func (x *DeviceList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_satellite_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceList.ProtoReflect.Descriptor instead.
func (*DeviceList) Descriptor() ([]byte, []int) {
	return file_proto_satellite_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceList) GetDevices() []*AudioDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type TrackEnded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEnded) Reset() {
	*x = TrackEnded{}
	mi := &file_proto_satellite_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEnded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEnded) ProtoMessage() {}

func (x *TrackEnded) ProtoReflect() protoreflect.Message {
	mi := &file_proto_satellite_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEnded.ProtoReflect.Descriptor instead.
func (*TrackEnded) Descriptor() ([]byte, []int) {
	return file_proto_satellite_proto_rawDescGZIP(), []int{6}
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Command
	//	*ServerMessage_RequestDevices
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_satellite_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_satellite_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_satellite_proto_rawDescGZIP(), []int{7}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ServerMessage) GetRequestDevices() *RequestDevices {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RequestDevices); ok {
			return x.RequestDevices
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Command struct {
	Command *Command `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type ServerMessage_RequestDevices struct {
	RequestDevices *RequestDevices `protobuf:"bytes,2,opt,name=request_devices,json=requestDevices,proto3,oneof"`
}

func (*ServerMessage_Command) isServerMessage_Payload() {}

func (*ServerMessage_RequestDevices) isServerMessage_Payload() {}

type Command struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Type     CommandType            `protobuf:"varint,1,opt,name=type,proto3,enum=satellite.CommandType" json:"type,omitempty"`
	Url      string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`             // PLAY
	Position float64                `protobuf:"fixed64,3,opt,name=position,proto3" json:"position,omitempty"` // PLAY (resume offset) / SEEK
	Volume   int32                  `protobuf:"varint,4,opt,name=volume,proto3" json:"volume,omitempty"`      // SET_VOLUME
	Device   string                 `protobuf:"bytes,5,opt,name=device,proto3" json:"device,omitempty"`       // SET_AUDIO_DEVICE
	// Track metadata — populated for PLAY so the satellite can log properly
	Id            string `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	Title         string `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string `protobuf:"bytes,8,opt,name=artist,proto3" json:"artist,omitempty"`
	Album         string `protobuf:"bytes,9,opt,name=album,proto3" json:"album,omitempty"`
	ReplayGain    string `protobuf:"bytes,10,opt,name=replay_gain,json=replayGain,proto3" json:"replay_gain,omitempty"` // SET_REPLAY_GAIN: "no", "track", or "album"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_satellite_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_satellite_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_satellite_proto_rawDescGZIP(), []int{8}
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_PLAY
}

func (x *Command) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Command) GetPosition() float64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Command) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Command) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Command) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Command) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *Command) GetReplayGain() string {
	if x != nil {
		return x.ReplayGain
	}
	return ""
}

type RequestDevices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDevices) Reset() {
	*x = RequestDevices{}
	mi := &file_proto_satellite_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDevices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDevices) ProtoMessage() {}

func (x *RequestDevices) ProtoReflect() protoreflect.Message {
	mi := &file_proto_satellite_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDevices.ProtoReflect.Descriptor instead.
func (*RequestDevices) Descriptor() ([]byte, []int) {
	return file_proto_satellite_proto_rawDescGZIP(), []int{9}
}

var File_proto_satellite_proto protoreflect.FileDescriptor

const file_proto_satellite_proto_rawDesc = "" +
	"\n" +
	"\x15proto/satellite.proto\x12\tsatellite\"\xaf\x02\n" +
	"\x10SatelliteMessage\x12=\n" +
	"\fregistration\x18\x01 \x01(\v2\x17.satellite.RegistrationH\x00R\fregistration\x124\n" +
	"\theartbeat\x18\x02 \x01(\v2\x14.satellite.HeartbeatH\x00R\theartbeat\x12.\n" +
	"\x05state\x18\x03 \x01(\v2\x16.satellite.PlayerStateH\x00R\x05state\x121\n" +
	"\adevices\x18\x04 \x01(\v2\x15.satellite.DeviceListH\x00R\adevices\x128\n" +
	"\vtrack_ended\x18\x05 \x01(\v2\x15.satellite.TrackEndedH\x00R\n" +
	"trackEndedB\t\n" +
	"\apayload\"T\n" +
	"\fRegistration\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\adevices\x18\x02 \x03(\v2\x16.satellite.AudioDeviceR\adevices\"1\n" +
	"\vAudioDevice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xcc\x01\n" +
	"\vPlayerState\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.satellite.StatusR\x06status\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x01R\bposition\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x01R\bduration\x12\x1f\n" +
	"\vcurrent_url\x18\x04 \x01(\tR\n" +
	"currentUrl\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x05R\x06volume\x12!\n" +
	"\faudio_device\x18\x06 \x01(\tR\vaudioDevice\".\n" +
	"\tHeartbeat\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\">\n" +
	"\n" +
	"DeviceList\x120\n" +
	"\adevices\x18\x01 \x03(\v2\x16.satellite.AudioDeviceR\adevices\"\f\n" +
	"\n" +
	"TrackEnded\"\x90\x01\n" +
	"\rServerMessage\x12.\n" +
	"\acommand\x18\x01 \x01(\v2\x12.satellite.CommandH\x00R\acommand\x12D\n" +
	"\x0frequest_devices\x18\x02 \x01(\v2\x19.satellite.RequestDevicesH\x00R\x0erequestDevicesB\t\n" +
	"\apayload\"\x88\x02\n" +
	"\aCommand\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.satellite.CommandTypeR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x01R\bposition\x12\x16\n" +
	"\x06volume\x18\x04 \x01(\x05R\x06volume\x12\x16\n" +
	"\x06device\x18\x05 \x01(\tR\x06device\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\b \x01(\tR\x06artist\x12\x14\n" +
	"\x05album\x18\t \x01(\tR\x05album\x12\x1f\n" +
	"\vreplay_gain\x18\n" +
	" \x01(\tR\n" +
	"replayGain\"\x10\n" +
	"\x0eRequestDevices*+\n" +
	"\x06Status\x12\b\n" +
	"\x04IDLE\x10\x00\x12\v\n" +
	"\aPLAYING\x10\x01\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x02*}\n" +
	"\vCommandType\x12\b\n" +
	"\x04PLAY\x10\x00\x12\t\n" +
	"\x05PAUSE\x10\x01\x12\b\n" +
	"\x04STOP\x10\x02\x12\b\n" +
	"\x04SEEK\x10\x03\x12\x0e\n" +
	"\n" +
	"SET_VOLUME\x10\x04\x12\x14\n" +
	"\x10SET_AUDIO_DEVICE\x10\x05\x12\n" +
	"\n" +
	"\x06RESUME\x10\x06\x12\x13\n" +
	"\x0fSET_REPLAY_GAIN\x10\a2X\n" +
	"\x10SatelliteService\x12D\n" +
	"\aConnect\x12\x1b.satellite.SatelliteMessage\x1a\x18.satellite.ServerMessage(\x010\x01B&Z$varakh.de/subsd/internal/satellitepbb\x06proto3"

var (
	file_proto_satellite_proto_rawDescOnce sync.Once
	file_proto_satellite_proto_rawDescData []byte
)

func file_proto_satellite_proto_rawDescGZIP() []byte {
	file_proto_satellite_proto_rawDescOnce.Do(func() {
		file_proto_satellite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_satellite_proto_rawDesc), len(file_proto_satellite_proto_rawDesc)))
	})
	return file_proto_satellite_proto_rawDescData
}

var file_proto_satellite_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_satellite_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_satellite_proto_goTypes = []any{
	(Status)(0),              // 0: satellite.Status
	(CommandType)(0),         // 1: satellite.CommandType
	(*SatelliteMessage)(nil), // 2: satellite.SatelliteMessage
	(*Registration)(nil),     // 3: satellite.Registration
	(*AudioDevice)(nil),      // 4: satellite.AudioDevice
	(*PlayerState)(nil),      // 5: satellite.PlayerState
	(*Heartbeat)(nil),        // 6: satellite.Heartbeat
	(*DeviceList)(nil),       // 7: satellite.DeviceList
	(*TrackEnded)(nil),       // 8: satellite.TrackEnded
	(*ServerMessage)(nil),    // 9: satellite.ServerMessage
	(*Command)(nil),          // 10: satellite.Command
	(*RequestDevices)(nil),   // 11: satellite.RequestDevices
}
var file_proto_satellite_proto_depIdxs = []int32{
	3,  // 0: satellite.SatelliteMessage.registration:type_name -> satellite.Registration
	6,  // 1: satellite.SatelliteMessage.heartbeat:type_name -> satellite.Heartbeat
	5,  // 2: satellite.SatelliteMessage.state:type_name -> satellite.PlayerState
	7,  // 3: satellite.SatelliteMessage.devices:type_name -> satellite.DeviceList
	8,  // 4: satellite.SatelliteMessage.track_ended:type_name -> satellite.TrackEnded
	4,  // 5: satellite.Registration.devices:type_name -> satellite.AudioDevice
	0,  // 6: satellite.PlayerState.status:type_name -> satellite.Status
	4,  // 7: satellite.DeviceList.devices:type_name -> satellite.AudioDevice
	10, // 8: satellite.ServerMessage.command:type_name -> satellite.Command
	11, // 9: satellite.ServerMessage.request_devices:type_name -> satellite.RequestDevices
	1,  // 10: satellite.Command.type:type_name -> satellite.CommandType
	2,  // 11: satellite.SatelliteService.Connect:input_type -> satellite.SatelliteMessage
	9,  // 12: satellite.SatelliteService.Connect:output_type -> satellite.ServerMessage
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_satellite_proto_init() }
func file_proto_satellite_proto_init() {
	if File_proto_satellite_proto != nil {
		return
	}
	file_proto_satellite_proto_msgTypes[0].OneofWrappers = []any{
		(*SatelliteMessage_Registration)(nil),
		(*SatelliteMessage_Heartbeat)(nil),
		(*SatelliteMessage_State)(nil),
		(*SatelliteMessage_Devices)(nil),
		(*SatelliteMessage_TrackEnded)(nil),
	}
	file_proto_satellite_proto_msgTypes[7].OneofWrappers = []any{
		(*ServerMessage_Command)(nil),
		(*ServerMessage_RequestDevices)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_satellite_proto_rawDesc), len(file_proto_satellite_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_satellite_proto_goTypes,
		DependencyIndexes: file_proto_satellite_proto_depIdxs,
		EnumInfos:         file_proto_satellite_proto_enumTypes,
		MessageInfos:      file_proto_satellite_proto_msgTypes,
	}.Build()
	File_proto_satellite_proto = out.File
	file_proto_satellite_proto_goTypes = nil
	file_proto_satellite_proto_depIdxs = nil
}
