// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: satellite.proto

package satellitepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SatelliteService_Connect_FullMethodName = "/satellite.SatelliteService/Connect"
)

// SatelliteServiceClient is the client API for SatelliteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SatelliteServiceClient interface {
	// Bidirectional stream: satellite dials server and holds this open.
	// Server pushes ServerMessage commands; satellite pushes SatelliteMessage state.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SatelliteMessage, ServerMessage], error)
}

type satelliteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSatelliteServiceClient(cc grpc.ClientConnInterface) SatelliteServiceClient {
	return &satelliteServiceClient{cc}
}

func (c *satelliteServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SatelliteMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SatelliteService_ServiceDesc.Streams[0], SatelliteService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SatelliteMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SatelliteService_ConnectClient = grpc.BidiStreamingClient[SatelliteMessage, ServerMessage]

// SatelliteServiceServer is the server API for SatelliteService service.
// All implementations must embed UnimplementedSatelliteServiceServer
// for forward compatibility.
type SatelliteServiceServer interface {
	// Bidirectional stream: satellite dials server and holds this open.
	// Server pushes ServerMessage commands; satellite pushes SatelliteMessage state.
	Connect(grpc.BidiStreamingServer[SatelliteMessage, ServerMessage]) error
	mustEmbedUnimplementedSatelliteServiceServer()
}

// UnimplementedSatelliteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSatelliteServiceServer struct{}

func (UnimplementedSatelliteServiceServer) Connect(grpc.BidiStreamingServer[SatelliteMessage, ServerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedSatelliteServiceServer) mustEmbedUnimplementedSatelliteServiceServer() {}
func (UnimplementedSatelliteServiceServer) testEmbeddedByValue()                          {}

// UnsafeSatelliteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SatelliteServiceServer will
// result in compilation errors.
type UnsafeSatelliteServiceServer interface {
	mustEmbedUnimplementedSatelliteServiceServer()
}

func RegisterSatelliteServiceServer(s grpc.ServiceRegistrar, srv SatelliteServiceServer) {
	// If the following call pancis, it indicates UnimplementedSatelliteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SatelliteService_ServiceDesc, srv)
}

func _SatelliteService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SatelliteServiceServer).Connect(&grpc.GenericServerStream[SatelliteMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SatelliteService_ConnectServer = grpc.BidiStreamingServer[SatelliteMessage, ServerMessage]

// SatelliteService_ServiceDesc is the grpc.ServiceDesc for SatelliteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SatelliteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "satellite.SatelliteService",
	HandlerType: (*SatelliteServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _SatelliteService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "satellite.proto",
}
